<?php


namespace Despark\Cms\Models;


use Despark\Cms\Admin\Interfaces\UploadImageInterface;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\UploadedFile;

/**
 * Class AdminModel
 */
class AdminModel extends Model
{

    /**
     * @var UploadedFile[] Files to save.
     */
    protected $files = [];

    /**
     * @var array
     */
    protected $dirtyFiles = [];

    /**
     * @param array $attributes
     * @return $this
     */
    public function fill(array $attributes)
    {
        // First fill the image and file attributes so they don't need to be guarded??
        if ($this instanceof UploadImageInterface) {
            foreach (array_keys($this->getImageFields()) as $imageFieldName) {
                if (array_key_exists($imageFieldName, $attributes)) {
                    $this->addFile($imageFieldName, $attributes[$imageFieldName]);

                    unset($attributes[$imageFieldName]);
                }
            }
        }

        return parent::fill($attributes); // TODO: Change the autogenerated stub
    }

    /**
     * Override is dirty so we can trigger update if we have dirty images.
     * @return array
     */
    public function getDirty()
    {
        $dirty = parent::getDirty();
        if (! empty($this->files)) {
            // We just set the ID to the same value to trigger the update.
            $dirty[$this->getKeyName()] = $this->getKey();
        }

        return $dirty;
    }

    /**
     * @param $fileId
     * @param UploadedFile $file
     */
    public function addFile($fileId, UploadedFile $file)
    {
        $this->files[$fileId] = $file;
    }

    /**
     * @return mixed
     */
    public function getFiles()
    {
        return $this->files;
    }

    /**
     * @return bool
     */
    public function hasImages()
    {
        return ($this instanceof UploadImageInterface && $this->images()->exists());
    }
}